### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by CodigoHacendado** [daz/live-f1#1]
Hi!

I'm trying to install live-f1 from source cloned via 'git clone'. But it seems that INSTALL file is missing. I try to install with automake and it fails. Are there any new way to install it?

Regards and thanks!

**Comment by daz** [comment]
What OS are you using? Try reading HACKING

**Comment by CodigoHacendado** [comment]
Fantastic! 'autoreconf -i' do the trick! 

I'm using Raspbian.

For newbies like me, 'autoreconf -i', 'automake', './configure', 'make', 'make install'.

Thanks a lot!

**Comment by daz** [comment]
👌🏼
